### PR TITLE
Adding GTFS Digest to Index.md

### PR DESCRIPTION
**Pull request by eliasmbd**
Adding the link to GTFS Digest on GTFS.org main page.

### CODE REVIEW

**Review by isabelle-dr — COMMENTED** [review]
I like the idea of adding some community resources directly to the landing page!

The "community" resources currently appear in two locations
1. https://gtfs.org/schedule/#getting-help-community
2. https://gtfs.org/resources/community/

In the intention of making information accessible, I'd like to propose that we don't add a third and instead, we move the whole [Getting Help and Community](https://gtfs.org/schedule/#getting-help-community) section to the landing page and add the GTFS Digest as the first bullet point. 

We can certainly use communication efforts to ensure the community is aware that this now exists! As a GTFS user visiting the site to look for community resources, I'd want to see all of them together and pick which the one(s) works best for me.

Additionally, we can add it to the [awesome transit list](https://github.com/CUTR-at-USF/awesome-transit), which is the source for the [Resources section](https://gtfs.org/resources/), so that it appears in both locations 🙂.

**Comment by eliasmbd** [comment]
@isabelle-dr I understand your concern and I think we should definetly bring this up during our 3 day hackathon in january.  This push is a temporary fix until then.

**Review by isabelle-dr — APPROVED** [review]
Approving this PR before I go on holidays so you can merge it this week.
Leaving it up to you to make modifications or not based on our discussion :)

**Comment by isabelle-dr** [comment]
@eliasmbd I believe this is your first PR on gtfs.org 🥳, so heads-up that we maintain a [translation backlog](https://github.com/MobilityData/gtfs.org/issues/234) that we keep up to date at all times.

People that merge a PR are responsible for updating the translation backlog ([example](
https://github.com/MobilityData/gtfs.org/pull/252#issuecomment-1864869347)), so don't forget to add this PR when you merge!

**Pull request merged**
