### PR TITLE
feat: updated Fares v2 examples

### PR DESCRIPTION
**Pull request by emmambd**
This is a draft PR to update the Fares v2 examples on gtfs.org to include examples from real feeds, improve formatting, and expand to include common fare media use cases. 

- [X] Modify structure of Fares v2 examples to improve readability
- [X] Update fare base implementation examples to include real data (thanks @tzujenchanmbd for your contribution to this!)
- [X] Add fare media examples
- [x] Add screenshots 
- [x] Add translations

### CODE REVIEW

**Review by isabelle-dr — COMMENTED** [review]
This looks great! 
One meta question: what is the reason you created two distinct "Base implementation" and "Fare Media" sections, as opposed to adding the fare media content in the same "Fares v2" example page?

I think "base implementation" doesn't mean much for stakeholders (except those who were involved in the PR).

**Review by tzujenchanmbd — COMMENTED** [review]
It looks great to me!

+1 regarding "base implementation"

**Comment by emmambd** [comment]
@tzujenchanmbd @isabelle-dr It was mainly because the list of examples was getting unwieldy and long without some kind of secondary categorization...I'll try keeping "Fare media" and removing "Base implementation" as secondary nav items

**Comment by emmambd** [comment]
@tzujenchanmbd @isabelle-dr Updates include 

- Adding relevant screenshots 
- Including `duration_limit_type` explanation 
- Changing the nav hierarchy so all Fares v2 examples are in the same section 

I'd like a final look at the `duration_limit_type` explanation after standup tomorrow — then I'll add all the translations and publish!

**Review by tzujenchanmbd — APPROVED** [review]
The duration_limit_type explanation looks good to me!

**Review by fredericsimard — APPROVED** [review]

**Pull request merged**
