### PR TITLE
Add Data Playbook

### PR DESCRIPTION
**Pull request by NomeQ**
Add link to Cal-ITP Data Playbook for publishing and sharing data

### CODE REVIEW

**Review by emmambd — COMMENTED** [review]
Hey @NomeQ ! This looks great - although I thought the intended plan was to embed this content directly into the gtfs.org website. Happy to include it as an external guide if that's the preference! If it is, it might be good to have a minified link for the Google Doc like from bit.ly so you can track views.

**Comment by NomeQ** [comment]
@emmambd I have now updated to link to its own, new page with all content on publishing and sharing embedded

**Review by isabelle-dr — COMMENTED** [review]
Thank you @NomeQ for this awesome contribution! A few comments:
I notice we have some redundancy about dataset publishing guidelines. 

I recommend we replace the following:

> Publish the feed by using one of the options below. 

With:

> Make the feed publicly available. See [Publishing and Sharing your GTFS](publishing/) for more information.

And then we remove the following pre-existing content from this page: 

> ## Making a Transit Feed Publicly Available
> <hr>
> Datasets should be published at a public, permanent URL, including the zip file name. (e.g., www.agency.org/gtfs/gtfs.zip). Ideally, the URL should be directly downloadable without requiring login to access the file, to facilitate download by consuming software applications. While it is recommended (and the most common practice) to make a GTFS dataset openly downloadable, if a data provider does need to control access to GTFS for licensing or other reasons, it is recommended to control access to the GTFS dataset using API keys, which will facilitate automatic downloads.
> 
> The web-server hosting GTFS data should be configured to correctly report the file modification date (see HTTP/1.1 - Request for Comments 2616, under Section 14.29).

**Comment by NomeQ** [comment]
Updated!

**Comment by isabelle-dr** [comment]
Thanks @NomeQ !

Merging this PR

**Review by isabelle-dr — APPROVED** [review]

**Pull request merged**
