### PR TITLE
fix: Set up Simpleen config and translation examples

### PR DESCRIPTION
**Pull request by emmambd**
This PR includes 

- Config for Simpleen's CLI tool 
- Translations for the About and Background pages 
- Manually changed items for the Realtime Reference pages in Korean and Traditional Chinese. These are items that should not be translated that were (which the glossary does not seem to identify correctly).

### CODE REVIEW

**Review by isabelle-dr — APPROVED** [review]
LGTM 🎉

**Comment by fredericsimard** [comment]
Looks great! Do you need me to merge this into `main`?

**Comment by emmambd** [comment]
@fredericsimard Yes please! Please let me know if there are any errors with the new pages in the build process.

**Comment by fredericsimard** [comment]
I'm still getting errors, something about the nav file...

```shell
err: WARNING  -  redirects plugin: 'schedule/revision-history' is not a valid markdown file!
err: WARNING  -  redirects plugin: 'realtime/revision-history' is not a valid markdown file!
err: WARNING  -  redirects plugin: 'realtime/extensions' is not a valid markdown file!
err: INFO     -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
err:   - about.DE.md
err:   - about.ES.md
err:   - about.FR.md
err:   - about.ID.md
err:   - about.JA.md
err:   - about.KO.md
err:   - about.PT-BR.md
err:   - about.ZH-TW.md
err:   - about.ZH.md
err:   - background.md
err:   - background.pt-br.md
err:   - background.zh-tw.md
err:   - realtime/examples/index.md
err: INFO     -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
err:   - about.DE.md
err:   - about.ES.md
err:   - about.FR.md
err:   - about.ID.md
err:   - about.JA.md
err:   - about.KO.md
err:   - about.PT-BR.md
err:   - about.ZH-TW.md
err:   - about.ZH.md
err:   - background.md
err:   - background.pt-br.md
err:   - background.zh-tw.md
err:   - realtime/examples/index.md
err: INFO     -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
err:   - about.DE.md
err:   - about.ES.md
err:   - about.FR.md
err:   - about.ID.md
err:   - about.JA.md
err:   - about.KO.md
err:   - about.PT-BR.md
err:   - about.ZH-TW.md
err:   - about.ZH.md
err:   - background.id.md
err:   - background.pt-br.md
err:   - background.zh-tw.md
err:   - realtime/examples/index.md
err: INFO     -  Translated navigation to id
err: INFO     -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
err:   - about.DE.md
err:   - about.ES.md
err:   - about.FR.md
err:   - about.ID.md
err:   - about.JA.md
err:   - about.KO.md
err:   - about.PT-BR.md
err:   - about.ZH-TW.md
err:   - about.ZH.md
err:   - background.de.md
err:   - background.pt-br.md
err:   - background.zh-tw.md
err:   - realtime/examples/index.md
err: INFO     -  Translated navigation to de
err: INFO     -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
err:   - about.DE.md
err:   - about.ES.md
err:   - about.FR.md
err:   - about.ID.md
err:   - about.JA.md
err:   - about.KO.md
err:   - about.PT-BR.md
err:   - about.ZH-TW.md
err:   - about.ZH.md
err:   - background.es.md
err:   - background.pt-br.md
err:   - background.zh-tw.md
err:   - realtime/examples/index.md
err: INFO     -  Translated navigation to es
err: INFO     -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
err:   - about.DE.md
err:   - about.ES.md
err:   - about.FR.md
err:   - about.ID.md
err:   - about.JA.md
err:   - about.KO.md
err:   - about.PT-BR.md
err:   - about.ZH-TW.md
err:   - about.ZH.md
err:   - background.fr.md
err:   - background.pt-br.md
err:   - background.zh-tw.md
err:   - realtime/examples/index.md
err: INFO     -  Translated navigation to fr
err: INFO     -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
err:   - about.DE.md
err:   - about.ES.md
err:   - about.FR.md
err:   - about.ID.md
err:   - about.JA.md
err:   - about.KO.md
err:   - about.PT-BR.md
err:   - about.ZH-TW.md
err:   - about.ZH.md
err:   - background.md
err:   - background.pt-br.md
err:   - background.zh-tw.md
err:   - realtime/examples/index.md
err: INFO     -  Translated navigation to pt_BR
err: INFO     -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
err:   - about.DE.md
err:   - about.ES.md
err:   - about.FR.md
err:   - about.ID.md
err:   - about.JA.md
err:   - about.KO.md
err:   - about.PT-BR.md
err:   - about.ZH-TW.md
err:   - about.ZH.md
err:   - background.ru.md
err:   - background.pt-br.md
err:   - background.zh-tw.md
err:   - realtime/examples/index.md
err: INFO     -  Translated navigation to ru
err: INFO     -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
err:   - about.DE.md
err:   - about.ES.md
err:   - about.FR.md
err:   - about.ID.md
err:   - about.JA.md
err:   - about.KO.md
err:   - about.PT-BR.md
err:   - about.ZH-TW.md
err:   - about.ZH.md
err:   - background.zh.md
err:   - background.pt-br.md
err:   - background.zh-tw.md
err:   - realtime/examples/index.md
err: INFO     -  Translated navigation to zh
err: INFO     -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
err:   - about.DE.md
err:   - about.ES.md
err:   - about.FR.md
err:   - about.ID.md
err:   - about.JA.md
err:   - about.KO.md
err:   - about.PT-BR.md
err:   - about.ZH-TW.md
err:   - about.ZH.md
err:   - background.md
err:   - background.pt-br.md
err:   - background.zh-tw.md
err:   - realtime/examples/index.md
err: INFO     -  Translated navigation to zh_TW
err: INFO     -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
err:   - about.DE.md
err:   - about.ES.md
err:   - about.FR.md
err:   - about.ID.md
err:   - about.JA.md
err:   - about.KO.md
err:   - about.PT-BR.md
err:   - about.ZH-TW.md
err:   - about.ZH.md
err:   - background.ja.md
err:   - background.pt-br.md
err:   - background.zh-tw.md
err:   - realtime/examples/index.md
err: INFO     -  Translated navigation to ja
err: INFO     -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
err:   - about.DE.md
err:   - about.ES.md
err:   - about.FR.md
err:   - about.ID.md
err:   - about.JA.md
err:   - about.KO.md
err:   - about.PT-BR.md
err:   - about.ZH-TW.md
err:   - about.ZH.md
err:   - background.ko.md
err:   - background.pt-br.md
err:   - background.zh-tw.md
err:   - realtime/examples/index.md
```

**Comment by fredericsimard** [comment]
@emmambd I think I see what the issue is. The translation names have to be added in the `      nav_translations:` section in the `mkdocs.yml` file, and that should add the translations.

**Comment by emmambd** [comment]
@fredericsimard I don't think that's it. `nav_translations` is for the navigation headings, which are translated for each language, but don't include the actual page content. You can see this as an example: https://gtfs.org/zh/about/

**Comment by fredericsimard** [comment]
@emmambd You're right. So why does it say it's missing from the nav configuration? Russian is translated, why not the rest?

**Comment by fredericsimard** [comment]
@emmambd I think I know. The file for About in Russian is spelled ru lowercase, same in the nav configuration, but for Japanese, the file is spelled JA uppercase, but lowercase in the configuration file... So UC/lc is respected.

**Comment by emmambd** [comment]
@fredericsimard Aaah that explains it - I think the file name is case sensitive. All the language codes needs to be in lower case, like `pr-bt`. I tried to change them a few times but git didn't accept the change.

**Comment by fredericsimard** [comment]
Did you do it on github.com or locally on your computer? You might need to delete them first, commit, then add them back with the changes.

**Pull request merged**
