### PR TITLE
fix traditional chinese translation

### PR DESCRIPTION
**Pull request by jameslinjl**
I was taking a look at the gtfs.org website translations, and noticed that the traditional Chinese translation was actually using simplified characters in a large portion of the translation.

### CODE REVIEW

**Comment by jameslinjl** [comment]
Hi @isabelle-dr @fredericsimard ! I'm interested in helping out with some GTFS related development and documentation. Let me know if there's a process that I should follow to get 👀 on any changes I'm hoping to contribute :)

**Comment by emmambd** [comment]
@jameslinjl As discussed during our call, thank you so much for taking the time to work on this contribution! We're going to talk to [Simpleen](https://simpleen.io/), the DeepL automated translation service we use, to see if we can resolve this issue with the traditional Chinese at the source before accepting manual translation contribution. I will likely share with you the "fixed" version when we resolve this so we can get your thoughts on the quality of the new and improved translation.

**Comment by emmambd** [comment]
Hi @jameslinjl! I'm going to reopen this PR and merge these changes after doing a big audit of our translations — we've decided to accept manual translations and commit to making sure we're only re-translating them when the original paragraph(s) change. We want to use these great contributions! Thanks again for doing this.

**Comment by emmambd** [comment]
Hi @jameslinjl! Working on getting these changes merged — could you make your repo public so we can see the conflicts? Then we can see how complex they are and decide how to fix them.

**Comment by jameslinjl** [comment]
@emmambd could you give it a try now?

**Comment by jameslinjl** [comment]
I had deleted the previous fork, so possible that i need to create a new PR based on the fork i just created

**Comment by emmambd** [comment]
Closing in favor of #144 - sorry for the wait @jameslinjl! Thanks for making the repo public - I was able to update the PR.

**Pull request closed without merging**
