### PR TITLE
[Monthly update] Nov-Dec 2024

### PR DESCRIPTION
**Pull request by Sergiodero**
This PR updates the following files in **EN, FR, JA and ES** to align with the latest changes in the google/transit repo:

- Schedule Reference
- Realtime Reference
- Realtime Protobuf page
- Realtime Protobuf file
- Realtime Revision History

Changes consist of:

- https://github.com/google/transit/pull/434
- https://github.com/google/transit/pull/439
- https://github.com/google/transit/pull/525

@skalexch do you mind reviewing the English files (just to confirm that changes look good) and the French translation? Thanks!

@fredericsimard could you take a quick look at the JA translation? thanks!

### CODE REVIEW

**Review by skalexch — CHANGES_REQUESTED** [review]
@Sergiodero most is fine except for one detail to fix in the french translation. It is "Ajout de" instead of just "ajout".
So:
- "Ajout de field_name" instead of "ajout field_name".
- "Ajout d'un"... Instead of "ajout un".

**Review by skalexch — APPROVED** [review]

**Comment by Sergiodero** [comment]
Thanks @skalexch FR text is now updated!

**Review by fredericsimard — APPROVED** [review]
LGTM!

**Comment by Sergiodero** [comment]
Thank you both @skalexch @fredericsimard! after finishing with the ES translation I'm now merging the changes.

**Pull request merged**
