### PR TITLE
Update flex.md

### PR DESCRIPTION
**Pull request by eliasmbd**
Changed the link to Airtable to remove the filtering menu from the view

### CODE REVIEW

**Review by tzujenchanmbd — APPROVED** [review]
Unable to preview the changes on my end. We can just try it, and revert if something goes wrong.

**Comment by fredericsimard** [comment]
@eliasmbd Does this still apply do you think?

**Comment by eliasmbd** [comment]
> @eliasmbd Does this still apply do you think?

Yes it does it just changes the airtable link

**Comment by fredericsimard** [comment]
Ok then we need a new PR because the file's location has changed.

**Comment by eliasmbd** [comment]
Made the changes here : https://github.com/MobilityData/gtfs.org/pull/526

**Pull request closed without merging**
