### PR TITLE
Fix schedule process revision history

### PR DESCRIPTION
**Pull request by fredericsimard**
This will fetch the content directly from Google's CHANGES.md and put it in the [/schedule/process](https://github.com/MobilityData/gtfs.org/blob/main/docs/schedule/process.md) page when compiling the site, only in the English translation.

Also removed "edit this page" and added dividers in the `fetchdata.sh` bash script.

### CODE REVIEW

**Comment by isabelle-dr** [comment]
Interesting! 

Could we do this for all pages where the source content is external? It makes it a lot easier to know where the content is coming from

**Comment by isabelle-dr** [comment]
e. g. 
- https://github.com/MobilityData/gtfs.org/blob/main/docs/schedule/reference.md
- https://github.com/MobilityData/gtfs.org/blob/main/docs/schedule/best-practices.md

**Review by isabelle-dr — APPROVED** [review]

**Comment by fredericsimard** [comment]
> Interesting!
> 
> Could we do this for all pages where the source content is external? It makes it a lot easier to know where the content is coming from

Yes, but the plug-in is very limited. Either it's the entire Markdown, or one section at a time. We can't modify the MD once it is integrated. Scott's script modifies links and some contents.

Also there is no translation possible, automatic or manual. It's copy and paste.

**Comment by emmambd** [comment]
@fredericsimard Did this remove the Github Action for this page any time there's a change on the external file now? 

My worry is that this will mean we can't keep track of what needs to be translated.

**Comment by fredericsimard** [comment]
@emmambd No, the script Scott created remains active and untouched. Apparently it was supposed to update the revision history, but wasn't in reality. So this fixes that.

**Pull request merged**
