### PR TITLE
Update Recently Merged Proposals Section in GTFS Schedule Changes

### PR DESCRIPTION
**Pull request by Sergiodero**
This PR updates the GTFS Schedule Changes page (schedule/changes/index.md) to include 7 PRs recently merged (from Jul to Nov 20230 into the spec into the Recently Merged Proposals section.

@isabelle-dr @tzujenchanmbd Could you take a look? Thanks!

### CODE REVIEW

**Review by isabelle-dr — COMMENTED** [review]
Thank you for working on this @Sergiodero!

It might be worth sharing that the initial idea for this page was to give a quick overview of the latest features available in GTFS (i. e. the "big" things, compared to the [Revision History](https://gtfs.org/schedule/process/#revision-history))
So among the new records you've added here, I think we could remove:
- fare media type 1
- clarify implied timezone
- specify shape_dist_traveled
- forbid sub-folders

Also, I am wondering when to remove older records also 🤔 so this list continues to be "Recent". 
Maybe we could try and have approx the past 2 years here?

**Review by tzujenchanmbd — COMMENTED** [review]
+1 keep major changes only, to differentiate Revision History page.

2 year sounds good to me, inclined to calendar year instead of fiscal year so we don't have to check too frequently.

**Comment by Sergiodero** [comment]
Hi! I've posted a [new commit](https://github.com/MobilityData/gtfs.org/pull/233/commits/ac072742ed836ae1fb482f01745d9d5294401ea1) to address your comments, this cuts the 4 suggested records from the previous commit and also deletes all spec changes made before 2022.

Could you take another look? @tzujenchanmbd @isabelle-dr thanks!

**Comment by tzujenchanmbd** [comment]
@Sergiodero suggest adding networks files one. Looks like it got adopted after opening this PR.

LGTM for other parts!

**Review by isabelle-dr — APPROVED** [review]
Good to go after adding networks.txt, thanks!

**Review by tzujenchanmbd — APPROVED** [review]

**Comment by isabelle-dr** [comment]
To whoever will be merging this PR: don't forget to update the [translation backlog](https://github.com/MobilityData/gtfs.org/issues/234)! Thanks :)

**Comment by isabelle-dr** [comment]
Added networks, merging. Thanks!

**Comment by isabelle-dr** [comment]
Added to the translation backlog

**Pull request merged**
